version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "type: dependencies"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "npm"
    directory: "/"
    labels:
      - "type: dependencies"
    schedule:
      interval: "daily"
    reviewers:
      - "VKumar786"
    open-pull-requests-limit: 10
    registries: "*"

  - package-ecosystem: "npm"
    directory: "packages/demo/"
    labels:
      - "type: dependencies"
    schedule:
      interval: "daily"
    reviewers:
      - "VKumar786"
    open-pull-requests-limit: 10
    registries: "*"

  - package-ecosystem: "npm"
    directory: "packages/demo-pack/"
    labels:
      - "type: dependencies"
    schedule:
      interval: "daily"
    reviewers:
      - "VKumar786"
    open-pull-requests-limit: 10
    registries: "*"

  - package-ecosystem: "npm"
    directory: "packages/preview/"
    labels:
      - "type: dependencies"
    schedule:
      interval: "daily"
    reviewers:
      - "VKumar786"
    open-pull-requests-limit: 10
    registries: "*"

  - package-ecosystem: "npm"
    directory: "packages/react-icons-ng/"
    labels:
      - "type: dependencies"
    schedule:
      interval: "daily"
    reviewers:
      - "VKumar786"
    open-pull-requests-limit: 10
    registries: "*"

  - package-ecosystem: "npm"
    directory: "packages/ts-test/"
    labels:
      - "type: dependencies"
    schedule:
      interval: "daily"
    reviewers:
      - "VKumar786"
    open-pull-requests-limit: 10
    registries: "*"

  - package-ecosystem: "npm"
    directory: "packages/webpack5-test/"
    labels:
      - "type: dependencies"
    schedule:
      interval: "daily"
    reviewers:
      - "VKumar786"
    open-pull-requests-limit: 10
    registries: "*"
